### ISSUE TITLE
Weird bug with WadTool

### ISSUE THREAD

**Issue by fearcraftor** [MontyTRC89/Tomb-Editor-Issues#1]
Error while importing a V130 WAD customized with WadMerger, with some more animations and objects from Chronicles

Sorry, the debugger is in French

************** Texte de l'exception **************
System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.ArgumentException: Un élément avec la même clé a déjà été ajouté.
   à System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   à System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   à System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   à TombLib.Wad.Tr4Wad.Tr4WadOperations.TaskMoveablesAndStatics() dans D:\Software\Tomb-Editor\TombLib\Wad\Tr4Wad\Tr4WadOperations.cs:ligne 237
   à System.Threading.Tasks.Task.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   à System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   à TombLib.Wad.Tr4Wad.Tr4WadOperations.ConvertTr4Wad(Tr4Wad old, List`1 soundPaths, IProgressReporter progressReporter) dans D:\Software\Tomb-Editor\TombLib\Wad\Tr4Wad\Tr4WadOperations.cs:ligne 317
   à WadTool.FormMain.butOpenSourceWad_Click(Object sender, EventArgs e) dans D:\Software\Tomb-Editor\WadTool\FormMain.cs:ligne 297
   à WadTool.FormMain.openSourceWADToolStripMenuItem_Click(Object sender, EventArgs e) dans D:\Software\Tomb-Editor\WadTool\FormMain.cs:ligne 56
   à System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   à System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   à System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   à System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   à System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   à System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   à System.Windows.Forms.ToolStrip.WndProc(Message& m)
   à System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Exception interne #0) System.ArgumentException: Un élément avec la même clé a déjà été ajouté.
   à System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   à System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   à System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   à TombLib.Wad.Tr4Wad.Tr4WadOperations.TaskMoveablesAndStatics() dans D:\Software\Tomb-Editor\TombLib\Wad\Tr4Wad\Tr4WadOperations.cs:ligne 237
   à System.Threading.Tasks.Task.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()<---

************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2600.0 built by: NET471REL1LAST
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WadTool
    Version de l'assembly : 1.0.4.0
    Version Win32 : 1.0.4.0
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/WadTool.exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DarkUI
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/DarkUI.DLL
----------------------------------------
SharpDX.Toolkit.Graphics
    Version de l'assembly : 2.4.2.0
    Version Win32 : 2.4.2
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/SharpDX.Toolkit.Graphics.DLL
----------------------------------------
SharpDX
    Version de l'assembly : 2.4.2.0
    Version Win32 : 2.4.2
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/SharpDX.DLL
----------------------------------------
SharpDX.DXGI
    Version de l'assembly : 2.4.2.0
    Version Win32 : 2.4.2
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/SharpDX.DXGI.DLL
----------------------------------------
SharpDX.Direct3D11
    Version de l'assembly : 2.4.2.0
    Version Win32 : 2.4.2
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/SharpDX.Direct3D11.DLL
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2600.0 built by: NET471REL1LAST
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
TombLib
    Version de l'assembly : 1.0.4.0
    Version Win32 : 1.0.4.0
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/TombLib.DLL
----------------------------------------
SharpDX.Toolkit
    Version de l'assembly : 2.4.2.0
    Version Win32 : 2.4.2
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/SharpDX.Toolkit.DLL
----------------------------------------
SharpDX.Toolkit.Compiler
    Version de l'assembly : 2.4.2.0
    Version Win32 : 2.4.2
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/SharpDX.Toolkit.Compiler.DLL
----------------------------------------
SharpDX.D3DCompiler
    Version de l'assembly : 2.4.2.0
    Version Win32 : 2.4.2
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/SharpDX.D3DCompiler.DLL
----------------------------------------
NLog
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.4.5422
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/NLog.DLL
----------------------------------------
Pfim
    Version de l'assembly : 0.4.4.0
    Version Win32 : 0.4.4
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/Pfim.DLL
----------------------------------------
System.Runtime
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.IO
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.IO.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.7.2556.0 built by: NET471REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
CH.SipHash
    Version de l'assembly : 1.0.2.0
    Version Win32 : 1.0.2.0
    CodeBase : file:///F:/Users/Florent/Documents/Tomb%20Editor/CH.SipHash.DLL
----------------------------------------

**Comment by fearcraftor** [comment]
Found out the reason, Wadmerger was not patched to include Chronicles objects names and my wad were exported with two empty names

**Comment by MontyTRC89** [comment]
I'm sad when those things happen :( For example, WadMerger is able also to create WADs with duplicate statics slots. Winroomedit worked well (maybe only with luck) but Tomb Editor raises an exception similar to yours. I have to fight with game's bugs and also with tool's bugs :(
