### ISSUE TITLE
Walls within Water cause Wall to disconnect

### ISSUE THREAD

**Issue by Raildex** [MontyTRC89/Tomb-Editor-Issues#10]
I have a Room which is filled with pillars. These pillars go out of the water.
The Walls however wave just like the water.
![shot001](https://user-images.githubusercontent.com/14938934/34314814-0479d9f0-e778-11e7-80f3-6fef729253b1.jpg)

**Comment by MontyTRC89** [comment]
This is fixed and ready for 1.0.5 update :)
