### ISSUE TITLE
"Invisibility" Texture Flag cannot be unset

### ISSUE THREAD

**Issue by Raildex** [MontyTRC89/Tomb-Editor-Issues#11]
The "Invisibility" Flag when Texturing cannot be unset, unless I copy a texture (ALT+Click on a Tile)

**Comment by MontyTRC89** [comment]
I will check this ;)

**Comment by ActuallyaDeviloper** [comment]
Appears to work for me.

**Comment by MontyTRC89** [comment]
Me too.
