### ISSUE TITLE
Enemies stuck on their spawn square (custom wads)

### ISSUE THREAD

**Issue by fearcraftor** [MontyTRC89/Tomb-Editor-Issues#12]
Hello all,

I think I've found an annoying bug affecting enemies, and this issue should come from TombEditor or WadTool while using customized wads.

Once they're triggered they are "stuck" inside their start square and cannot walk further, even if they're correctly animated, and also that they're attacking Lara once she's close to them.

Furthermore, I've made a couple of tests : 
- building the same level with Room Edit, the same **v1** Wad file and old tools ==> Enemies work fine
- importing this sane v1 project into Tomb Editor and play it ==> Bug

The wad file I use is a V130 made from scratch with Wadmerger

My conclusion is there's probably an issue once converting in Prj2 or Wad2 

I'm even more confused as all TR4 Core levels I've imported and converted seems to be fine regarding their baddies.

How can I help you ?

Cheers

**Comment by MontyTRC89** [comment]
Hi :) Please send me PRJ/WAD/TGA. This way I can inspect boxes and overlaps and solve the issue ;)

**Comment by fearcraftor** [comment]
[TE_issue_#12_fearcraftor.zip](https://github.com/MontyTRC89/Tomb-Editor-Issues/files/1590945/TE_issue_.12_fearcraftor.zip)

**Comment by MontyTRC89** [comment]
This is a bug related to boxes and overlaps generation. With a flat room, you have only one box and zero overlaps. The problem is managing correctly this case. I will fix it for the next updae 1.0.5. ;) You can try this yourself, increasing one sector by 1 click. Five boxes will be created, with correct overlaps, and enemies will attack you ;)

**Comment by MontyTRC89** [comment]
Bug fixed ;)

**Comment by fearcraftor** [comment]
Great ! I think a single very flat room was far from your expectations. 

Btw : I'm very delighted by this editor and loving using it. It brought me back the envy to make TR levels :)
