### ISSUE TITLE
Editing E/D Segments of Floor Directions are switched

### ISSUE THREAD

**Issue by Raildex** [MontyTRC89/Tomb-Editor-Issues#15]
![grafik](https://user-images.githubusercontent.com/14938934/34650474-253e81c6-f3c2-11e7-9c63-cda76dbd783d.png)

![grafik](https://user-images.githubusercontent.com/14938934/34650478-30cbaa50-f3c2-11e7-9b10-eb4696980cee.png)

I can edit the Floor Segmentation only when the X appears, and not when the Arrows appear

**Comment by MontyTRC89** [comment]
I can't replicate the problem :( Could you create a video?

**Comment by Raildex** [comment]
It only happens when the selected Wall is a Portal.

**Comment by MontyTRC89** [comment]
Seems to be fixed.
