### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by TokyoSU** [MontyTRC89/Tomb-Editor-Issues#17]
Possibility to Adding another release for Linux ?

**Comment by ActuallyaDeviloper** [comment]
We are currently far from supporting other operating system.
One of the main reasons is that we use DirectX for rendering.

Maybe you can try to run TE with Wine?

**Comment by TokyoSU** [comment]
I will try it but not today.
thanks :)

**Comment by TokyoSU** [comment]
Working ?
d3dcompiler_43.dll not found at launch.

**Comment by MontyTRC89** [comment]
You can find the lib in native directory of the package. Just pay attention to architecture (x86/x64).
