### ISSUE TITLE
Trigger Placement is unintuitive

### ISSUE THREAD

**Issue by Raildex** [MontyTRC89/Tomb-Editor-Issues#2]
TRLE remembers the currently selected object and when you want to Trigger (default Trigger) this object, you simply have to press the Pink Button.

In Tomb Editor however, i have to press the "+" button and have to manually(!!!) select the Object I want to trigger.
Even for a simple door this is really tiresome.

Edit:
It looks like TE remembers the object, but only as long as I am in the same room

**Comment by MontyTRC89** [comment]
Thank you, I will check this ;)

**Comment by ActuallyaDeviloper** [comment]
This is actually intended behaviour. Notice that TE has a unified object selection system.
If you move between rooms using a portal, the portal is now selected.

I added object bookmarking in the upcoming version to solve the annoyance for all those who want to use the portal navigation. Press shift for bookmarking an object/use the object for a trigger.
