### ISSUE TITLE
Fix bugs in geometry editing

### ISSUE THREAD

**Issue by MontyTRC89** [MontyTRC89/Tomb-Editor-Issues#4]
Some combinations give strange results. Some examples reported in TRF.

**Comment by MontyTRC89** [comment]
Many of them fixed with update 1.0.5. I'll keep this opened for more wrong cases if they will be.

**Comment by ActuallyaDeviloper** [comment]
Is this still present?

**Comment by MontyTRC89** [comment]
Seems to be fixed :)
